"""Added hashed_password column to app table

Revision ID: 4a36008c16c5
Revises: 18354ecf92ac
Create Date: 2026-05-18 14:42:31.334525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a36008c16c5'
down_revision: Union[str, Sequence[str], None] = '18354ecf92ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'hashed_password')
    # ### end Alembic commands ###
